/**
 * Multilingual i18n Configuration for SatQuery AI.
 * Supports English + All 22 Official Eighth Schedule Languages of India.
 */

export const LANGUAGES = [
    { code: 'en', name: 'English', native: 'English' },
    { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
    { code: 'te', name: 'Telugu', native: 'తెలుగు' },
    { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
    { code: 'bn', name: 'Bengali', native: 'বাংলা' },
    { code: 'mr', name: 'Marathi', native: 'मराठी' },
    { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
    { code: 'kn', name: 'Kannada', native: 'కన్నడ' },
    { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
    { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
    { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
    { code: 'as', name: 'Assamese', native: 'অসমীয়া' },
    { code: 'ur', name: 'Urdu', native: 'اردو' },
    { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्' },
    { code: 'ne', name: 'Nepali', native: 'नेपाली' },
    { code: 'gom', name: 'Konkani', native: 'कोंकणी' },
    { code: 'mai', name: 'Maithili', native: 'मैथिली' },
    { code: 'mni', name: 'Manipuri (Meitei)', native: 'মৈতৈলোন্' },
    { code: 'brx', name: 'Bodo', native: 'बर' },
    { code: 'doi', name: 'Dogri', native: 'डोगरी' },
    { code: 'ks', name: 'Kashmiri', native: 'कश्मीरी' },
    { code: 'sd', name: 'Sindhi', native: 'سنڌي' },
    { code: 'sat', name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ' }
];

export const TRANSLATIONS = {
    en: {
        app_title: "SatQuery AI",
        tagline: "Ask. Analyze. Understand.",
        welcome_marquee: "Welcome to SatQuery AI — Agentic Remote-Sensing Assistant for Earth Observation & Multimodal Analysis",
        nav_home: "Home",
        nav_about: "About",
        nav_single_image: "Single Image",
        nav_multi_image: "Multi-Image Change",
        nav_gis_map: "GIS Map",
        nav_learn: "Learn RS",
        nav_contact: "Contact Us",
        section_analyze: "ANALYZE",
        section_monitor: "MONITOR",
        section_explore: "EXPLORE",
        section_learn: "LEARN & REPORTS",
        hero_title: "A clearer view of satellite imagery.",
        hero_subtitle: "Observe the present. Explore the possibilities. Understand the evidence.",
        hero_badge: "AGENTIC REMOTE-SENSING ASSISTANT",
        btn_single_image: "Single Image Analysis",
        btn_multi_image: "Multi-Image Change",
        btn_explore_map: "Explore GIS Map",
        btn_start_monitoring: "Start Monitoring",
        supported_modalities: "SUPPORTED SATELLITE SENSOR MODALITIES",
        optical_sensors: "OPTICAL SENSORS",
        multispectral_sensors: "MULTISPECTRAL SENSORS",
        sar_sensors: "SAR (SYNTHETIC APERTURE RADAR)",
        optical_desc: "Visible RGB band imaging for surface mapping, visual scene interpretation, and land cover structure.",
        multispectral_desc: "Vegetation canopy chlorophyll measurement (NDVI), surface water extraction (NDWI), and urban concrete analysis (NDBI).",
        sar_desc: "Active microwave pulse observation. Penetrates cloud cover, fog, and darkness for flood and structural backscatter detection.",
        single_title: "Single Image Analysis & BigEarthNet AI Chatbot",
        single_subtitle: "Upload a satellite image in PNG, JPG, or JPEG format. The BigEarthNet-19 fine-tuned AI model activates instantly.",
        dropzone_title: "Click or Drag & Drop Satellite Image",
        dropzone_subtitle: "Supports PNG, JPG, JPEG, TIFF",
        sample_tiles_title: "OR SELECT A SAMPLE TILE:",
        chatbot_title: "SatQuery AI Assistant",
        chatbot_subtitle: "Ask any question about the uploaded satellite image.",
        input_placeholder: "Ask SatQuery about this image... e.g. 'What is the dominant land cover class?'",
        btn_ask: "Ask",
        multi_title: "Multi-Image Change Detection & Comparison",
        multi_subtitle: "Upload Observation T1 and Observation T2 (PNG/JPG/JPEG). Bi-temporal model compares land cover modifications.",
        obs_t1: "OBSERVATION T1 (BASELINE)",
        obs_t2: "OBSERVATION T2 (CONVERSION)",
        swipe_title: "INTERACTIVE SWIPE COMPARISON SLIDER",
        land_cover_title: "BigEarthNet Land-Cover Classification",
        map_title: "Interactive GIS Map & Continuous AOI Watch",
        groundwater_title: "Indicative Groundwater / Borewell Potential Assessment",
        rocket_title: "Rocket & Orbital Payload Tracking",
        prompt_title: "Interactive Prompt Quality Evaluator",
        quiz_title: "Interactive Remote Sensing Quiz",
        reports_title: "Generate Printable PDF Audit Report",
        about_title: "About SatQuery AI",
        contact_title: "Contact Us"
    },
    hi: {
        app_title: "SatQuery AI",
        tagline: "पूछें। विश्लेषण करें। समझें।",
        welcome_marquee: "सैटक्वेरी एआई में आपका स्वागत है — पृथ्वी अवलोकन के लिए एजेंटिक रिमोट-सेंसिंग सहायक",
        nav_home: "होम",
        nav_about: "हमारे बारे में",
        nav_single_image: "एकल छवि",
        nav_multi_image: "बहु-छवि परिवर्तन",
        nav_gis_map: "जीआईएस मानचित्र",
        nav_learn: "सीखें",
        nav_contact: "संपर्क करें",
        section_analyze: "विश्लेषण",
        section_monitor: "निगरानी",
        section_explore: "अन्वेषण",
        section_learn: "सीखें एवं रिपोर्ट",
        hero_title: "उपग्रह इमेजरी का एक स्पष्ट दृश्य।",
        hero_subtitle: "वर्तमान का निरीक्षण करें। संभावनाओं का अन्वेषण करें। साक्ष्यों को समझें।",
        hero_badge: "एजेंटिक रिमोट-सेंसिंग सहायक",
        btn_single_image: "एकल छवि विश्लेषण",
        btn_multi_image: "बहु-छवि परिवर्तन",
        btn_explore_map: "जीआईएस मानचित्र देखें",
        btn_start_monitoring: "निगरानी शुरू करें",
        supported_modalities: "समर्थित उपग्रह सेंसर मोडैलिटीज़",
        optical_sensors: "ऑप्टिकल सेंसर",
        multispectral_sensors: "मल्टीस्पेक्ट्रल सेंसर",
        sar_sensors: "एसएआर (सिंथेटिक अपर्चर रडार)",
        optical_desc: "सतह मानचित्रण और दृश्य व्याख्या के लिए दृश्यमान आरजीबी बैंड इमेजरी।",
        multispectral_desc: "वनस्पति कैनोपी क्लोरोफिल मापन (NDVI) और जल निकाय निष्कर्षण (NDWI)।",
        sar_desc: "सक्रिय माइक्रोवेव पल्स। बाढ़ और संरचनात्मक पहचान के लिए बादलों को भेदता है।",
        single_title: "एकल छवि विश्लेषण और बिगअर्थनेट एआई चैटबॉट",
        single_subtitle: "PNG, JPG, या JPEG प्रारूप में उपग्रह छवि अपलोड करें। बिगअर्थनेट-19 मॉडल तुरंत सक्रिय होता है।",
        dropzone_title: "उपग्रह छवि अपलोड करने के लिए क्लिक करें या ड्रैग करें",
        dropzone_subtitle: "PNG, JPG, JPEG, TIFF समर्थित",
        sample_tiles_title: "या एक नमूना छवि चुनें:",
        chatbot_title: "सैटक्वेरी एआई सहायक",
        chatbot_subtitle: "अपलोड की गई उपग्रह छवि के बारे में कोई भी प्रश्न पूछें।",
        input_placeholder: "इस छवि के बारे में पूछें... उदा. 'मुख्य भूमि आवरण क्या है?'",
        btn_ask: "पूछें",
        multi_title: "बहु-छवि परिवर्तन पहचान और तुलना",
        multi_subtitle: "अवलोकन T1 और T2 अपलोड करें। द्वि-अस्थायी मॉडल भूमि आवरण परिवर्तनों की तुलना करता है।",
        obs_t1: "अवलोकन T1 (बेसलाइन)",
        obs_t2: "अवलोकन T2 (रूपांतरण)",
        swipe_title: "इंटरएक्टिव स्वाइप तुलना स्लाइडर",
        land_cover_title: "बिगअर्थनेट भूमि-आवरण वर्गीकरण",
        map_title: "इंटरएक्टिव जीआईएस मानचित्र और सतत निगरानी",
        groundwater_title: "संकेतात्मक भूजल / बोरवेल क्षमता मूल्यांकन",
        rocket_title: "रॉकेट और कक्षीय पेलोड ट्रैकिंग",
        prompt_title: "इंटरएक्टिव प्रॉम्प्ट गुणवत्ता मूल्यांकनकर्ता",
        quiz_title: "इंटरएक्टिव रिमोट सेंसिंग क्विज",
        reports_title: "प्रिंट करने योग्य पीडीएफ ऑडिट रिपोर्ट बनाएं",
        about_title: "सैटक्वेरी एआई के बारे में",
        contact_title: "संपर्क करें"
    },
    te: {
        app_title: "SatQuery AI",
        tagline: "అడగండి. విశ్లేషించండి. అర్థం చేసుకోండి.",
        welcome_marquee: "SatQuery AI కి స్వాగతం — భూ పరిశీలన కోసం ఏజెంటిక్ రిమోట్-సెన్సింగ్ అసిస్టెంట్",
        nav_home: "హోమ్",
        nav_about: "మా గురించి",
        nav_single_image: "సింగిల్ ఇమేజ్",
        nav_multi_image: "మల్టీ-ఇమేజ్ మార్పు",
        nav_gis_map: "GIS మ్యాప్",
        nav_learn: "నేర్చుకోండి",
        nav_contact: "సంప్రదించండి",
        section_analyze: "విశ్లేషణ",
        section_monitor: "మొనిటరింగ్",
        section_explore: "అన్వేషణ",
        section_learn: "లెర్నింగ్ & రిపోర్ట్స్",
        hero_title: "శాటిలైట్ ఇమేజరీ యొక్క స్పష్టమైన వీక్షణం.",
        hero_subtitle: "ప్రస్తుతాన్ని పరిశీలించండి. అవకాశాలను అన్వేషించండి. ఆధారాలను అర్థం చేసుకోండి.",
        hero_badge: "ఏజెంటిక్ రిమోట్-సెన్సింగ్ అసిస్టెంట్",
        btn_single_image: "సింగిల్ ఇమేజ్ విశ్లేషణ",
        btn_multi_image: "మల్టీ-ఇమేజ్ మార్పు",
        btn_explore_map: "GIS మ్యాప్ పరిశీలించండి",
        btn_start_monitoring: "మొనిటరింగ్ ప్రారంభించండి",
        supported_modalities: "మద్దతు ఉన్న శాటిలైట్ సెన్సార్ రకాలు",
        optical_sensors: "ఆప్టికల్ సెన్సార్లు",
        multispectral_sensors: "మల్టీస్పెక్ట్రల్ సెన్సార్లు",
        sar_sensors: "SAR (సింథటిక్ అపెర్చర్ రాడార్)",
        optical_desc: "ఉపరితల మ్యాపింగ్ మరియు దృశ్య విశ్లేషణ కోసం విజిబుల్ RGB బ్యాండ్ ఇమేజింగ్.",
        multispectral_desc: "వృక్షసంపద పత్రహరితం కొలత (NDVI) మరియు జల వనరుల విశ్లేషణ (NDWI).",
        sar_desc: "రేడియో తరంగాల పరిశీలన. మబ్బులు మరియు చీకటిని ఛేదించి వరదలను గుర్తిస్తుంది.",
        single_title: "సింగిల్ ఇమేజ్ విశ్లేషణ & BigEarthNet AI చాట్‌బాట్",
        single_subtitle: "PNG, JPG, లేదా JPEG ఆకృతిలో శాటిలైట్ చిత్రాన్ని అప్‌లోడ్ చేయండి.",
        dropzone_title: "చిత్రాన్ని అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి లేదా డ్రాగ్ చేయండి",
        dropzone_subtitle: "PNG, JPG, JPEG మద్దతు ఉంది",
        sample_tiles_title: "లేదా శాంపిల్ చిత్రాన్ని ఎంచుకోండి:",
        chatbot_title: "SatQuery AI అసిస్టెంట్",
        chatbot_subtitle: "అప్‌లోడ్ చేసిన చిత్రం గురించి ఏదైనా ప్రశ్న అడగండి.",
        input_placeholder: "ఈ చిత్రం గురించి అడగండి... ఉదా. 'ప్రధాన భూమి రకం ఏమిటి?'",
        btn_ask: "అడగండి",
        multi_title: "మల్టీ-ఇమేజ్ మార్పుల గుర్తింపు",
        multi_subtitle: "పరిశీలన T1 మరియు T2 అప్‌లోడ్ చేయండి.",
        obs_t1: "పరిశీలన T1 (బేస్‌లైన్)",
        obs_t2: "పరిశీలన T2 (మార్పు)",
        swipe_title: "స్వాఇప్ పోలిక స్లైడర్",
        land_cover_title: "BigEarthNet భూమి వర్గీకరణ",
        map_title: "GIS మ్యాప్ & నిరంతర మొనిటరింగ్",
        groundwater_title: "భూగర్భ జల సామర్థ్య అంచనా",
        rocket_title: "రాకెట్ ట్రాకింగ్",
        prompt_title: "ప్రాంప్ట్ మూల్యాంకనం",
        quiz_title: "రిమోట్ సెన్సింగ్ క్విజ్",
        reports_title: "PDF రిపోర్ట్ జనరేట్ చేయండి",
        about_title: "SatQuery AI గురించి",
        contact_title: "సంప్రదించండి"
    },
    ta: {
        app_title: "SatQuery AI",
        tagline: "கேளுங்கள். பகுப்பாய்வு செய்யுங்கள். புரிந்து கொள்ளுங்கள்.",
        welcome_marquee: "SatQuery AI க்கு வரவேற்கிறோம் — செயற்கைக்கோள் தரவு பகுப்பாய்வு உதவியாளர்",
        nav_home: "முகப்பு",
        nav_about: "பற்றி",
        nav_single_image: "ஒற்றை படம்",
        nav_multi_image: "பல பட மாற்றம்",
        nav_gis_map: "GIS வரைபடம்",
        nav_learn: "கற்க",
        nav_contact: "தொடர்பு கொள்ள",
        section_analyze: "பகுப்பாய்வு",
        section_monitor: "கண்காணிப்பு",
        section_explore: "ஆராய்க",
        section_learn: "கற்றல் & அறிக்கைகள்",
        hero_title: "செயற்கைக்கோள் படங்களின் தெளிவான பார்வை.",
        hero_subtitle: "நிகழ்காலத்தைக் கவனியுங்கள். சாத்தியக்கூறுகளை ஆராயுங்கள்.",
        hero_badge: "செயற்கைக்கோள் தரவு உதவியாளர்",
        btn_single_image: "ஒற்றை பட பகுப்பாய்வு",
        btn_multi_image: "பல பட மாற்றம்",
        btn_explore_map: "வரைபடத்தை ஆராய்க",
        btn_start_monitoring: "கண்காணிப்பைத் தொடங்கு",
        single_title: "ஒற்றை பட பகுப்பாய்வு & BigEarthNet AI சாட்பாட்",
        dropzone_title: "செயற்கைக்கோள் படத்தை பதிவேற்ற கிளிக் செய்யவும்",
        chatbot_title: "SatQuery AI உதவியாளர்",
        input_placeholder: "கேள்வி கேட்கவும்...",
        btn_ask: "கேள்"
    },
    bn: {
        app_title: "SatQuery AI",
        tagline: "জিজ্ঞাসা করুন। বিশ্লেষণ করুন। বুঝুন।",
        welcome_marquee: "SatQuery AI-তে স্বাগতম — কৃত্রিম উপগ্রহ তথ্য বিশ্লেষণ সহকারী",
        nav_home: "হোম",
        nav_about: "আমাদের সম্পর্কে",
        nav_single_image: "একক ছবি",
        nav_multi_image: "বহু-ছবি পরিবর্তন",
        nav_gis_map: "জিআইএস মানচিত্র",
        nav_learn: "শিখুন",
        nav_contact: "যোগাযোগ",
        section_analyze: "বিশ্লেষণ",
        section_monitor: "পর্যবেক্ষণ",
        section_explore: "অনুসন্ধান",
        section_learn: "শিক্ষা ও রিপোর্ট",
        hero_title: "উপগ্রহ চিত্রের স্পষ্ট দৃশ্য।",
        hero_subtitle: "বর্তমান পর্যবেক্ষণ করুন। সম্ভাবনা উন্মোচন করুন।",
        hero_badge: "উপগ্রহ তথ্য সহকারী",
        btn_single_image: "একক ছবি বিশ্লেষণ",
        single_title: "একক ছবি বিশ্লেষণ এবং BigEarthNet এআই চ্যাটবট",
        dropzone_title: "উপগ্রহ ছবি আপলোড করতে ক্লিক করুন",
        chatbot_title: "SatQuery এআই সহকারী",
        input_placeholder: "প্রশ্ন জিজ্ঞাসা করুন...",
        btn_ask: "জিজ্ঞাসা করুন"
    },
    mr: {
        app_title: "SatQuery AI",
        tagline: "विचारा. विश्लेषण करा. समजा.",
        welcome_marquee: "SatQuery AI मध्ये आपले स्वागत आहे — उपग्रह डेटा विश्लेषण सहाय्यक",
        nav_home: "होम",
        nav_about: "आमच्याबद्दल",
        nav_single_image: "सिंगल इमेज",
        nav_multi_image: "मल्टी-इमेज बदल",
        nav_gis_map: "जीआयएस नकाशा",
        nav_learn: "शिका",
        nav_contact: "संपर्क करा",
        section_analyze: "विश्लेषण",
        section_monitor: "निरीक्षण",
        section_explore: "शोध",
        hero_title: "उपग्रह प्रतिमांचे स्पष्ट दृश्य.",
        single_title: "सिंगल इमेज विश्लेषण आणि BigEarthNet AI चॅटबॉट",
        dropzone_title: "प्रतिमा अपलोड करण्यासाठी क्लिक करा",
        btn_ask: "विचारा"
    }
};

export function getTranslation(langCode, key) {
    const dict = TRANSLATIONS[langCode] || TRANSLATIONS['hi'] || TRANSLATIONS['en'];
    return dict[key] || TRANSLATIONS['en'][key] || key;
}
